Wdp220601 12
odevpl/wdp220601 pull request #11
Opened 2022-06-13 18:59 UTC by MichPlewa

-add camparing onClick
-add sticking compering bar

2022-06-15 16:47 UTC, arcinech requested changes
Ważne: Sekcja compare pod innymi elementami style do poprawy.
Opcjonalne: Przycisk na karcie produktu tylko dodaje produkt do compare bez możliwości ponownego usunięcia przez kliknięcie w ten sam przycisk.

2022-06-15 16:47 UTC, arcinech commented on src/redux/productsRedux.js
> +};
Action creatory w jednej linii będą bardziej czytelne.

2022-06-15 16:47 UTC, arcinech commented on src/components/common/ProductBox/ProductBox.js
> +      dispatch(addCompare(id));
Masz logikę tylko dodającą stan compare true.
Przydałoby się mieć również możliwość usunięcia produktu z compare przez ponowne naciśnięcie przycisku compare.

2022-06-17 12:00 UTC, MichPlewa commented on src/components/common/ProductBox/ProductBox.js
> +      dispatch(addCompare(id));
Wiem, ale zadanie tego nie przewidziało. podam to do PM o nowe zadanie, gdzie się to zmieni :)

2022-06-17 12:03 UTC, MichPlewa commented on src/redux/productsRedux.js
> +};
musiałem zapomnieć jak robiłem tu consol.loga :)

2022-06-17 12:03 UTC, MichPlewa commented on src/components/features/CompareBar/CompareBar.module.scss
> +.navbar {
dobry pomysł.

2022-06-17 12:10 UTC, MichPlewa commented on src/components/common/ProductBox/ProductBox.js
> +      dispatch(addCompare(id));
dobra pogadałem z PM. zajmę się tym.

2022-06-17 12:19 UTC, MichPlewa commented
Fixed all remakrs.

2022-06-17 12:42 UTC, arcinech approved these changes

2022-06-19 08:04 UTC, merged